spring:
  application:
    name: simple-stack-system-template
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    pool-size: 5
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      #      file-size-threshold: 100KB
      enabled: true

server:
  port: "${SERVER_PORT:8080}"

management:
  server:
    port: "${MANAGEMENT_SERVER_PORT:8081}"
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

jwt:
  issuer: simple-stack-system-template
  token-key: "${JWT_TOKEN_KEY}"
  token-duration: "PT24H"

jwt-issue-new-token-before-expiration-duration: "PT5M"
