spring:
  thymeleaf:
    cache: false
    mode: HTML
    encoding: "UTF-8"
    prefix: file:static/templates/
  web:
    resources: # Static resources
      static-locations: [ "file:static/assets", "file:static/target/assets" ]
      cache:
        period: 0

jwt:
  token-key: "qxg+hQ=="

email:
  postmark-api-token: "postmark-api-token"
  postmark-webhook-token: "postmark-webhook-token"
  frontend-domain: "http://localhost:8080"
