spring:
  application:
    name: simple-stack-system-template
  datasource:
    url: "${DB_URL}"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
    pool-size: 5
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      #      file-size-threshold: 100KB
      enabled: true

server:
  port: "${SERVER_PORT:8080}"

management:
  server:
    port: "${MANAGEMENT_SERVER_PORT:8081}"
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

jwt:
  issuer: simple-stack-system-template
  token-key: "${JWT_TOKEN_KEY}"
  token-duration: "PT24H"

jwt-issue-new-token-before-expiration-duration: "PT5M"

email:
  fake-server: true
  templates-dir: "${TEMPLATES_DIR:/email-templates}"
  postmark-api-token: "${POSTMARK_API_TOKEN}"
  postmark-webhook-token: "${POSTMARK_WEBHOOK_TOKEN}"
  frontend-domain: "https://binaryigor.com"
  from-email:
    name: "Simple Stack System Template App"
    email: "app@binaryigor.com"
  user:
    # TODO: prettier url
    user-activation-url: "activate-account"
    sign-up-url: "sign-up"
    email-change-confirmation-url: "user"
    password-reset-url: "forgot-password"
    new-password-url: "set-new-password"
