{
 "title": "Alerts",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Quick Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Guardian health check",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"guardian\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus health check",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert manager health check",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus-alertmanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker metrics collectors health check",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - monitoring_collector_up_timestamp_seconds",
     "legendFormat": "{{machine}}"
    }
   ]
  },
  {
   "title": "Alerts in the last 15m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(monitoring_alerts_total{status=\"firing\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts in the last 6h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(monitoring_alerts_total{status=\"firing\"}[6h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts in the last 24h",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(monitoring_alerts_total{status=\"firing\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "New alerts in time",
   "type": "timeseries",
   "description": "Count of new alerts, appearing in the 15 minutes time window",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (status) (increase(monitoring_alerts_total[$__rate_interval]))",
     "legendFormat": "{{label_alertname}}"
    }
   ]
  },
  {
   "title": "Alerts in time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (alertname, job, application, alertstate) (increase(ALERTS[$__rate_interval]))",
     "legendFormat": "{{alertname}}:{{job}}:{{application}}:{{alertstate}}"
    }
   ]
  },
  {
   "title": "New alerts details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(monitoring_alert_timestamp_seconds{status=\"firing\"} * 1000) > $__from < $__to",
     "legendFormat": "{{label_alertname}}"
    }
   ]
  }
 ]
}