{
 "title": "Application",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "application",
    "query": {
     "query": "label_values(monitoring_application_up_timestamp_seconds, application)"
    }
   },
   {
    "name": "machine",
    "label": "machine",
    "query": {
     "query": "label_values(monitoring_application_up_timestamp_seconds{application=\"$application\"}, machine)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "App instance health check",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - monitoring_application_up_timestamp_seconds{application=\"$application\", machine=\"$machine\"}",
     "legendFormat": "{{source}}-{{application}}-{{instance_id}}"
    }
   ]
  },
  {
   "title": "App instance uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - monitoring_application_started_at_timestamp_seconds{application=\"$application\", machine=\"$machine\"}",
     "legendFormat": "{{source}}-{{application}}-{{instance_id}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "monitoring_application_used_memory_bytes{application=\"$application\", machine=\"$machine\"} / monitoring_application_max_memory_bytes{application=\"$application\", machine=\"$machine\"}",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "CPU  usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "monitoring_application_cpu_usage_percent{application=\"$application\", machine=\"$machine\"}",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory space usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "monitoring_application_used_memory_bytes{application=\"$application\", machine=\"$machine\"}",
     "legendFormat": "Used memory"
    },
    {
     "expr": "monitoring_application_max_memory_bytes{application=\"$application\", machine=\"$machine\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Logs warnings/errors timestamps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "(monitoring_application_logs_warning_timestamp_seconds{application=\"$application\", machine=\"$machine\"} * 1000)  > $__from < $__to",
     "legendFormat": "Warnings"
    },
    {
     "expr": "(monitoring_application_logs_error_timestamp_seconds{application=\"$application\", machine=\"$machine\"} * 1000)  > $__from < $__to",
     "legendFormat": "Errors"
    }
   ]
  }
 ]
}