{
 "title": "Container",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(container_up_timestamp_seconds, container)"
    }
   },
   {
    "name": "machine",
    "label": "machine",
    "query": {
     "query": "label_values(container_up_timestamp_seconds{container=\"$container\"}, machine)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container instance health check",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_up_timestamp_seconds{container=\"$container\", machine=\"$machine\"}",
     "legendFormat": "{{source}}-{{container}}"
    }
   ]
  },
  {
   "title": "Container instance uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_started_at_timestamp_seconds{container=\"$container\", machine=\"$machine\"}",
     "legendFormat": "{{source}}-{{container}}-{{instance_id}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_used_memory_bytes{container=\"$container\", machine=\"$machine\"} / container_max_memory_bytes{container=\"$container\", machine=\"$machine\"}",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "CPU  usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_cpu_usage_percent{container=\"$container\", machine=\"$machine\"}",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Memory space usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_used_memory_bytes{container=\"$container\", machine=\"$machine\"}",
     "legendFormat": "Used memory"
    },
    {
     "expr": "container_max_memory_bytes{container=\"$container\", machine=\"$machine\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "Log events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (level) (increase(container_logs_total{container=\"$container\", machine=\"$machine\"}[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}