{
 "title": "Coturn",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(turn_total_allocations, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Received Bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(turn_traffic_rcvb{job=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Sent Bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(turn_traffic_sentb{job=\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "turn_total_allocations{job=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(turn_traffic_rcvb{job=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Sent Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(turn_traffic_sentb{job=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}