global:
  scrape_interval: 30s
  scrape_timeout: 5s
  evaluation_interval: 30s

rule_files:
  - alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:${ALERTMANAGER_PORT}

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: prometheus-alertmanager
    static_configs:
      - targets: [ 'localhost:${ALERTMANAGER_PORT}' ]
  - job_name: main-node
    static_configs:
      - targets: [ 'localhost:${NODE_EXPORTER_PORT}' ]
  - job_name: main
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'localhost' ]
  - job_name: metrics-and-logs-collector
    metrics_path: ""
    static_configs:
      - targets: [ 'localhost:${METRICS_AND_LOGS_COLLECTOR_PORT}' ]
