apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    url: http://localhost:9090
    isDefault: false
    editable: false
    version: 2
  - name: application-postgres-db
    type: postgres
    url: $DATASOURCE_APPLICATION_DATABASE_URL
    database: $DATASOURCE_APPLICATION_DATABASE
    user: $DATASOURCE_APPLICATION_DATABASE_USER
    secureJsonData:
      password: $DATASOURCE_APPLICATION_DATABASE_PASSWORD
    jsonData:
      sslmode: require
      maxOpenConns: 2
      maxIdleConns: 1
      connMaxLifetime: 14400
      postgresVersion: 1400
      timeInterval: 1m
    isDefault: false
    editable: false
    version: 2