spring:
  application:
    name: simple-stack-system-template-guardian

server:
  port: "${SERVER_PORT:9999}"

management:
  server:
    port: "${MANAGEMENT_SERVER_PORT:10000}"
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

