{
 "title": "Event",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "event_id",
    "label": "Event id",
    "query": "SELECT id FROM event.event ORDER BY start_at DESC LIMIT 1000"
   },
   {
    "name": "meeting_id",
    "label": "Meeting id",
    "query": "SELECT id FROM event.meeting WHERE event_id = '$event_id'"
   }
  ]
 },
 "panels": [
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  id, name, description, start_at, end_at\nFROM\n  event.event\nORDER BY start_at DESC\nLIMIT 1000;\n"
    }
   ]
  },
  {
   "title": "Event stats",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT invited, accepted, entered, in_meeting, waiting_for_meeting,\n  (SELECT COUNT(*) FROM event.meeting WHERE event_id = '$event_id') AS meetings\nFROM (\n  SELECT\n  COUNT(*) as invited,\n  SUM(CASE WHEN response = 'ACCEPTED' THEN 1 ELSE 0 END) AS accepted\n  FROM event.invitation WHERE event_id = '$event_id'\n) AS invitation, \n(\n SELECT \n SUM(CASE WHEN entered_at IS NULL THEN 0 ELSE 1 END) AS entered,\n SUM(CASE WHEN (available_at > (NOW() - interval '20 minute') AND available = false) THEN 1 ELSE 0 END) AS in_meeting,\n SUM(CASE WHEN (available_at > (NOW() - interval '1 minute') AND available = true) THEN 1 ELSE 0 END) AS waiting_for_meeting\n FROM event.participant WHERE event_id = '$event_id'\n) AS event_participant;\n"
    }
   ]
  },
  {
   "title": "Event meetings",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  em.id, em.created_at, mp.user_id, u.name, u.email, mp.entered_at, mp.left_at\nFROM\n  event.meeting AS em\nINNER JOIN event.meeting_participant AS mp\nON em.id = mp.meeting_id\nINNER JOIN \"user\".\"user\" AS u\nON mp.user_id = u.id\nWHERE event_id = '$event_id' AND (meeting_id IN (${meeting_id:singlequote}))\nORDER BY created_at DESC\n"
    }
   ]
  }
 ]
}